DROP  SCHEMA IF EXISTS mvc CASCADE ;
CREATE SCHEMA IF NOT EXISTS mvc ;


CREATE TABLE mvc.CONTACT(
  ID BIGSERIAL ,
  FIRST_NAME VARCHAR(60) NOT NULL,
  LAST_NAME VARCHAR(40) NOT NULL,
  BIRTH_DATE DATE,
  DESCRIPTION VARCHAR(2000),
  PHOTO BYTEA,
  UNIQUE (FIRST_NAME,LAST_NAME),
  PRIMARY KEY (ID)
);