CREATE SCHEMA IF NOT EXISTS audit;

CREATE TABLE audit.CONTACT_AUDIT(
  ID BIGSERIAL NOT NULL ,
  FIRST_NAME VARCHAR(60) NOT NULL,
  LAST_NAME VARCHAR(40) NOT NULL,
  BIRTH_DATE DATE,
  VERSION INT NOT NULL DEFAULT 0,
  CREATED_BY VARCHAR(20),
  CREATED_DATE TIMESTAMP,
  LAST_MODIFIED_BY VARCHAR(20),
  LAST_MODIFIED_DATE TIMESTAMP,
  UNIQUE (FIRST_NAME,LAST_NAME),
  PRIMARY KEY (ID)

);
CREATE TABLE audit.CONTACT_AUDIT_H(
  ID INTEGER NOT NULL ,
  FIRST_NAME VARCHAR(60) NOT NULL,
  LAST_NAME VARCHAR(40) NOT NULL,
  BIRTH_DATE DATE,
  VERSION INT NOT NULL DEFAULT 0,
  CREATED_BY VARCHAR(20),
  CREATED_DATE TIMESTAMP,
  LAST_MODIFIED_BY VARCHAR(20),
  LAST_MODIFIED_DATE TIMESTAMP,
  AUDIT_REVISION INTEGER NOT NULL ,
  ACTION_ТYPE INTEGER,
  AUDIT_REVISION_END INTEGER,
  AUDIT_REVISION_END_TS TIMESTAMP,
  UNIQUE (ID,AUDIT_REVISION),
  PRIMARY KEY (ID,AUDIT_REVISION)
);
CREATE TABLE audit.REVINFO (
 REVTSTMP BIGINT NOT NULL,
 REV BIGSERIAL NOT NULL ,
 PRIMARY KEY (REVTSTMP, REV)

) ;



insert into audit.CONTACT_AUDIT (first_name, last_name, birth_date) values ('Chris', 'Schaefer', '1981-05-03');
insert into audit.CONTACT_AUDIT(first_name, last_name, birth_date) values ('Scott', 'Tiger', '1990-11-02');
insert into audit.CONTACT_AUDIT (first_name, last_name, birth_date) values ('John', 'Smith', '1964-02-28');
